Cleanup vendor patch script
* Cleanup comments
* Add checking before doing the process for overlay and enforce permissions prop
* add "then" variable for gnss as 32 libaries wont being detected

diff --git a/POST_sGSI_Patches/patch.d/03-vendor-patch b/POST_sGSI_Patches/patch.d/03-vendor-patch
--- a/POST_sGSI_Patches/patch.d/03-vendor-patch
+++ b/POST_sGSI_Patches/patch.d/03-vendor-patch
@@ -4,25 +4,27 @@
 
 print "Patching vendor..."
 
-echo "8.1 to P Vendor Blobs Patcher by Erfan Abdi"
+echo "8.1 to P Vendor Blobs Patcher by Erfan Abdi,dev-haran and fxsheep"
 echo "Make sure vendor is mounted before flashing this"
 
-#OnePlus manifest Patches
+# OnePlus Patches
 
-if ! grep -Fq "vendor.oneplus.camera.CameraHIDL" /vendor/manifest.xml
+if ! grep -Fxq "vendor.oneplus.camera.CameraHIDL" /vendor/manifest.xml
 then
     sed -i -e ':a' -e 'N' -e '$!ba' -e 's/<\/manifest>/    <hal format="hidl">\n        <name>vendor.oneplus.camera.CameraHIDL<\/name>\n        <transport>hwbinder<\/transport>\n        <version>1.0<\/version>\n        <interface>\n            <name>IOnePlusCameraProvider<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@1.0::IOnePlusCameraProvider\/default<\/fqname>\n    <\/hal>\n    <hal format="hidl">\n        <name>vendor.oneplus.faceunlock.hal<\/name>\n        <transport>hwbinder<\/transport>\n        <version>1.0<\/version>\n        <interface>\n            <name>IFaceUnlockNativeService<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@1.0::IFaceUnlockNativeService\/default<\/fqname>\n    <\/hal>\n    <hal format="hidl">\n        <name>vendor.oneplus.fingerprint.extension<\/name>\n        <transport>hwbinder<\/transport>\n        <version>1.0<\/version>\n        <interface>\n            <name>IVendorFingerprintExtensions<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@1.0::IVendorFingerprintExtensions\/default<\/fqname>\n    <\/hal>\n    <hal format="hidl">\n        <name>vendor.oneplus.hardware.display<\/name>\n        <transport>hwbinder<\/transport>\n        <version>1.0<\/version>\n        <interface>\n            <name>IOneplusDisplay<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@1.0::IOneplusDisplay\/default<\/fqname>\n    <\/hal>\n    <hal format="hidl">\n        <name>vendor.oneplus.hardware.drmkey<\/name>\n        <transport>hwbinder<\/transport>\n        <version>1.0<\/version>\n        <interface>\n            <name>IOneplusDrmKey<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@1.0::IOneplusDrmKey\/default<\/fqname>\n    <\/hal>\n    <hal format="hidl">\n        <name>vendor.oneplus.hardware.ifaa<\/name>\n        <transport>hwbinder<\/transport>\n        <version>2.0<\/version>\n        <interface>\n            <name>IOneplusIfaa<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@2.0::IOneplusIfaa\/default<\/fqname>\n    <\/hal>\n    <hal format="hidl">\n        <name>vendor.oneplus.hardware.param<\/name>\n        <transport>hwbinder<\/transport>\n        <version>1.0<\/version>\n        <interface>\n            <name>IOneplusParam<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@1.0::IOneplusParam\/default<\/fqname>\n    <\/hal>\n    <hal format="hidl">\n        <name>vendor.oneplus.hardware.wifi<\/name>\n        <transport>hwbinder<\/transport>\n        <version>1.1<\/version>\n        <interface>\n            <name>IOneplusWifi<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@1.1::IOneplusWifi\/default<\/fqname>\n    <\/hal>\n<\/manifest>/g' /vendor/manifest.xml
 fi
 
-#Global Vendor Patches
+# Global Vendor Patches
 
-#Disable PrivApp enforce
-sed -i 'ro.control_privapp_permissions=enforce/d' /vendor/build.prop
+# Disable PrivApp enforce
+if ! grep -Fxq "ro.control_privapp_permissions=enforce" /vendor/build.prop
+then
+    sed -i 'ro.control_privapp_permissions=enforce/d' /vendor/build.prop
+fi
 
 # Enable GPU Profiling
 if ( getprop ro.vendor.product.device | grep -Fxq '(riva,rolex)' );then
     GET_XIAOMI=1
-else
     if [ -n "$GET_XIAOMI" ];then
     echo "debug.hwui.profile=true" >> /vendor/build.prop
 fi
@@ -32,7 +34,7 @@ then
     echo "sys.use_fifo_ui=1" >> /vendor/build.prop
 fi
 
-#WIFI
+# WIFI
 if ! grep -Fq "android.hardware.wifi.hostapd" /vendor/manifest.xml
 then
     wifirc=`grep -H -r "/vendor/bin/hw/wpa_supplicant" /vendor/etc/init/hw/* | cut -d: -f1`
@@ -43,7 +45,7 @@ then
     sed -i -e ':a' -e 'N' -e '$!ba' -e 's/<\/manifest>/    <hal format="hidl">\n        <name>android.hardware.wifi.hostapd<\/name>\n        <transport>hwbinder<\/transport>\n        <version>1.0<\/version>\n        <interface>\n            <name>IHostapd<\/name>\n            <instance>default<\/instance>\n        <\/interface>\n        <fqname>@1.0::IHostapd\/default<\/fqname>\n    <\/hal>\n<\/manifest>/g' /vendor/manifest.xml
 fi
 
-#NFC
+# NFC
 if [ -e "/vendor/etc/libnfc-brcm.conf" ]; then
     mv /vendor/etc/libnfc-brcm.conf /vendor/etc/libnfc-nci.conf
     sed -i '/APPL_TRACE_LEVEL/d' /vendor/etc/libnfc-nci.conf
@@ -52,25 +54,29 @@ if [ -e "/vendor/etc/libnfc-brcm.conf" ]; then
     echo "NFC_DEBUG_ENABLED=0" >> /vendor/etc/libnfc-nci.conf
 fi
 
-#GPS
+# GPS
 if [ -e "/vendor/lib/vendor.qti.gnss@1.0_vendor.so" ]; then
     sed -i "s/android.hardware.gnss@1.0.so/Wndroid.hardware.gnss@1.0.so/" /vendor/lib/vendor.qti.gnss@1.0_vendor.so
     sed -i "s/android.hardware.gnss@1.0.so/Wndroid.hardware.gnss@1.0.so/" /vendor/lib/vendor.qti.gnss@1.0.so
+else
+    sed -i "s/android.hardware.gnss@1.0.so/Wndroid.hardware.gnss@1.0.so/" /vendor/lib64/vendor.qti.gnss@1.0_vendor.so
+    sed -i "s/android.hardware.gnss@1.0.so/Wndroid.hardware.gnss@1.0.so/" /vendor/lib64/vendor.qti.gnss@1.0.so
 fi
-sed -i "s/android.hardware.gnss@1.0.so/Wndroid.hardware.gnss@1.0.so/" /vendor/lib64/vendor.qti.gnss@1.0_vendor.so
-sed -i "s/android.hardware.gnss@1.0.so/Wndroid.hardware.gnss@1.0.so/" /vendor/lib64/vendor.qti.gnss@1.0.so
+
 if [ -e "/vendor/bin/slim_daemon" ]; then
     sed -i "s/android.hardware.gnss@1.0.so/Wndroid.hardware.gnss@1.0.so/" /vendor/bin/slim_daemon
     sed -i "s/android.frameworks.sensorservice@1.0.so/Wndroid.frameworks.sensorservice@1.0.so/" /vendor/bin/slim_daemon
     rm -rf /vendor/bin/slim_daemon
 fi
 
-#Cleanup overlays
-mv /vendor/overlay/framework-res__auto_generated_rro.apk /vendor/overlay/framework-res__auto_generated_rro.apk2
-rm -rf /vendor/overlay/*.apk
-mv /vendor/overlay/framework-res__auto_generated_rro.apk2 /vendor/overlay/framework-res__auto_generated_rro.apk
+# Cleanup overlays
+if [ -e "/vendor/overlay" ]; then
+    mv /vendor/overlay/framework-res__auto_generated_rro.apk /vendor/overlay/framework-res__auto_generated_rro.apk2
+    rm -rf /vendor/overlay/*.apk
+    mv /vendor/overlay/framework-res__auto_generated_rro.apk2 /vendor/overlay/framework-res__auto_generated_rro.apk
+fi
 
-#Xiaomi FP Patches
+# Xiaomi FP Patches
 fphal=`ls /vendor/bin/hw/android.hardware.biometrics.fingerprint*`
 if grep -Fxq "_ZN7android16IKeystoreService11asInterfaceERKNS_2spINS_7IBinderEEE" $fphal
 then
@@ -82,19 +88,19 @@ if [ ! -f /data/system/users/0/settings_fingerprint.xml ]; then
     rm -rf /persist/data/finger_*
 fi
 
-#LG RIL
+# LG RIL
 if [ -e "/vendor/lib64/vendor.lge.hardware.radio@1.0.so" ]; then
     sed -i "s/android.hardware.radio@1.0.so/Wndroid.hardware.radio@1.0.so/" /vendor/lib/vendor.lge.hardware.radio@1.0.so
     sed -i "s/android.hardware.radio@1.0.so/Wndroid.hardware.radio@1.0.so/" /vendor/lib64/vendor.lge.hardware.radio@1.0.so
 fi
 
-#Moto RIL
+# Moto RIL
 if [ -e "/vendor/lib64/libsensorndkbridge.so" ]; then
     sed -i "s/android.hardware.sensors@1.0.so/Wndroid.hardware.sensors@1.0.so/" /vendor/lib/libsensorndkbridge.so
     sed -i "s/android.hardware.sensors@1.0.so/Wndroid.hardware.sensors@1.0.so/" /vendor/lib64/libsensorndkbridge.so
 fi
 
-#Motorola camera
+# Motorola camera
 if [ -e "/vendor/lib/libjustshoot.so" ]; then
     sed -i "s/android.frameworks.sensorservice@1.0.so/Wndroid.frameworks.sensorservice@1.0.so/" /vendor/lib/libjustshoot.so
     sed -i "s/libutils.so/libWtils.so/" /vendor/lib/libjustshoot.so
@@ -105,7 +111,7 @@ if [ -e "/vendor/lib/libmot_gpu_mapper.so" ]; then
     sed -i "s/libutils.so/libWtils.so/" /vendor/lib/libmot_gpu_mapper.so
 fi
 
-#Whyred camera
+# Whyred camera
 if [ -e "/vendor/lib/libvidhance_gyro.so" ]; then
     sed -i "s/android.frameworks.sensorservice@1.0.so/Wndroid.frameworks.sensorservice@1.0.so/" /vendor/lib/libvidhance_gyro.so
 fi
